# Generated by Django 5.2.13 on 2026-04-11 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_categoria_usuario_produto_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='produtos.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicoproduto',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='produtos.empresa'),
        ),
        migrations.AddField(
            model_name='produto',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.empresa'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('empresa', 'nome')},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='usuario',
        ),
        migrations.CreateModel(
            name='MembroEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('admin', 'Administrador'), ('funcionario', 'Funcionário')], default='funcionario', max_length=20)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='produtos.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'unique_together': {('empresa', 'usuario')},
            },
        ),
    ]
